### ISSUE TITLE
Limited space in activity description

### ISSUE THREAD

**Issue by meersjo** [lbedford/lbwreg.django#19]
The available space for activity description is fairly limited. Suggest changing to CLOB type in database.

**Comment by lbedford** [comment]
from random internet searches, it seems CLOB is an Oracle type, and the mysql translation is text. We are limiting to 400 chars for the moment, easy enough to change.

Though I suspect there's something else going on as Katje's event name was truncated at much less than the 100 chars it should have.

**Comment by lbedford** [comment]
Django refused to do migrations in the setup I had. I have hacked around it and the lengths are now more reasonable (more than 20 chars for a description).
