### ISSUE TITLE
Commenting on activity without entering subject redirects to frontpage

### ISSUE THREAD

**Issue by meersjo** [lbedford/lbwreg.django#21]
Offending behaviour:
After commenting on an activity and omitting a message subject, I am sent to http://lbw.draiocht.net/registration/ .

Expected behaviour:
Either accept the message without subject, or show an error message; but stay on the same page.

**Comment by lbedford** [comment]
added a required tag to subject, which makes the browser insist on it.
Made the save_message code more resilient.
