### ISSUE TITLE
Incorrect list levels

### ISSUE THREAD

**Issue by meersjo** [lbedford/lbwreg.django#22]
On http://lbw.draiocht.net/registration/ , "Wiltz 2015" is visually shown as a sub-activity of "Talybont-on-Usk", where they should be on the same level.

![lbwreg jango incorrect indent](https://cloud.githubusercontent.com/assets/1178044/9036282/58b73564-39e0-11e5-95b7-27fbda57b52f.png)

**Comment by lbedford** [comment]
opening a <ul> per registered LBW doesn't work well.
